// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtFDRukpikma3EGQM1bborZl_RC3L_Mg',
    appId: '1:717671222223:web:2640d891b97e2e8b03e0ba',
    messagingSenderId: '717671222223',
    projectId: 'group34-28a20',
    authDomain: 'group34-28a20.firebaseapp.com',
    storageBucket: 'group34-28a20.appspot.com',
    measurementId: 'G-YZ7PS135LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhpV9JBONRp7DcoNjRQi-iMCbHfS0Ierk',
    appId: '1:717671222223:android:8f5054fa7535ab8003e0ba',
    messagingSenderId: '717671222223',
    projectId: 'group34-28a20',
    storageBucket: 'group34-28a20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4tgx1hJFOGsmCi_ayJ6BTVAO2Jl6Hf50',
    appId: '1:717671222223:ios:092950983ea22ca403e0ba',
    messagingSenderId: '717671222223',
    projectId: 'group34-28a20',
    storageBucket: 'group34-28a20.appspot.com',
    androidClientId: '717671222223-r6oo3p1p76fhhekpdp71ecnemres36b3.apps.googleusercontent.com',
    iosClientId: '717671222223-gqp4jt75c4ruv3ej77riuapas9lt1snt.apps.googleusercontent.com',
    iosBundleId: 'com.example.group34firbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4tgx1hJFOGsmCi_ayJ6BTVAO2Jl6Hf50',
    appId: '1:717671222223:ios:092950983ea22ca403e0ba',
    messagingSenderId: '717671222223',
    projectId: 'group34-28a20',
    storageBucket: 'group34-28a20.appspot.com',
    androidClientId: '717671222223-r6oo3p1p76fhhekpdp71ecnemres36b3.apps.googleusercontent.com',
    iosClientId: '717671222223-gqp4jt75c4ruv3ej77riuapas9lt1snt.apps.googleusercontent.com',
    iosBundleId: 'com.example.group34firbase',
  );
}
